FROM public.ecr.aws/l1s7l7p8/all-in-one-ai-stable-diffusion-webui-inference:latest

COPY serve /opt/ml/code
COPY stable-diffusion-webui /opt/ml/code/

RUN git clone https://github.com/xieyongliang/sd-webui-controlnet.git /opt/ml/code/extensions/sd-webui-controlnet