FROM python:3.10-slim

RUN pip3 install pandas torch safetensors pytorch_lightning
ENV PYTHONUNBUFFERED=TRUE

RUN mkdir -p /opt/ml/processing/input
RUN mkdir -p /opt/ml/processing/output

ENTRYPOINT ["python3"]
