FROM ghcr.io/allenai/pytorch:1.12.1-cuda11.3-python3.9-v1.2.0

RUN apt update
RUN apt install wget git python3 python3-venv
RUN apt install libgl1-mesa-glx -y
RUN pip install opencv-python-headless

RUN mkdir -p /opt/ml/code
COPY stable-diffusion-webui /opt/ml/code/
COPY serve /opt/ml/code
COPY config.json /opt/ml/code

WORKDIR /opt/ml/code