FROM ghcr.io/allenai/pytorch:1.12.1-cuda11.3-python3.9-v1.2.0

RUN apt update
RUN apt install wget git -y
RUN apt install libgl1-mesa-glx -y
RUN pip install opencv-python-headless

RUN mkdir -p /opt/ml/code
COPY stable-diffusion-webui /opt/ml/code/
COPY webui /opt/ml/code

RUN git clone https://github.com/xieyongliang/sd_dreambooth_extension.git /opt/ml/code/extensions/sd_dreambooth_extension

WORKDIR /opt/ml/code

ENTRYPOINT ["python3", "webui"]