FROM python:3.8-slim

RUN apt update
RUN apt install wget git -y
RUN apt install libgl1-mesa-glx -y
RUN apt install build-essential -y
RUN pip3 install pandas torch safetensors pytorch_lightning
ENV PYTHONUNBUFFERED=TRUE

RUN mkdir -p /opt/ml/processing/input
RUN mkdir -p /opt/ml/processing/output

ENTRYPOINT ["python3"]
