AWSTemplateFormatVersion: 2010-09-09
Description: Template for SSM Parameter Store

Parameters:    
  S3Bucket:
    Description: S3 Bucket of assets
    Type: String

  S3Key:
    Description: S3 Bucket of assets
    Type: String

  SageMakerRole:
    Type: String
    Description: SageMaker Role Arn

  CreatePipelineHelperLambdaArn:
    Type: String
    Description: CreatePipelineHelper Lambda Arn

  ChinaRegion: 
    Description: Check if the stack to be in CN Region
    Type: String
    Default: false
    AllowedValues: [ true, false ]

Conditions:
  Globally: !Equals [ false, !Ref ChinaRegion ]

Resources:
  Parameter1:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /all_in_one_ai/config/meta/algorithms/yolov5/greengrass/components/com.example.yolov5/template
      Type: String
      Value: !Sub s3://${S3Bucket}/${S3Key}algorithms/yolov5/greengrass/components/com.example.yolov5/template

  Parameter2:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /all_in_one_ai/config/meta/algorithms/yolov5/greengrass/components/com.example.yolov5/deployment/deployment_policy
      Type: String
      Value: !Sub |
        {
          "failureHandlingPolicy": "ROLLBACK",
          "componentUpdatePolicy": {
            "action": "NOTIFY_COMPONENTS",
            "timeoutInSeconds": 60
          },
          "configurationValidationPolicy": {
            "timeoutInSeconds": 60
          }
        }

  Parameter3:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /all_in_one_ai/config/meta/algorithms/yolov5/greengrass/components/com.example.yolov5/deployment/iot_job_configurations
      Type: String
      Value: !Sub |
        {
          "jobExecutionsRolloutConfig": {
            "exponentialRate": {
              "baseRatePerMinute": 5,
              "incrementFactor": 2,
              "rateIncreaseCriteria": {
                "numberOfNotifiedThings": 10
              }
            },
            "maximumPerMinute": 50
          },
          "abortConfig": {
            "criteriaList": [
              {
                "action": "CANCEL",
                "failureType": "ALL",
                "minNumberOfExecutedThings": 100,
                "thresholdPercentage": 5
              }
            ]
          },
          "timeoutConfig": {
            "inProgressTimeoutInMinutes": 5
          }
        }

  Parameter4:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /all_in_one_ai/config/meta/sagemaker_role_arn
      Type: String
      Value: !Ref SageMakerRole

  Parameter5:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /all_in_one_ai/config/meta/algorithms/yolov5paddleocr/industrialmodels
      Type: String
      Value: !Sub s3://${S3Bucket}/${S3Key}algorithms/yolov5paddleocr/industrialmodels/

  Parameter6:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /all_in_one_ai/config/meta/algorithms/yolov5gluoncv/industrialmodels
      Type: String
      Value: !Sub s3://${S3Bucket}/${S3Key}algorithms/yolov5gluoncv/industrialmodels/

  Parameter7:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /all_in_one_ai/config/meta/api_table
      Type: String
      Value: all_in_one_ai_api
  
  Parameter8:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /all_in_one_ai/config/meta/endpoint_table
      Type: String
      Value: all_in_one_ai_endpoint

  Parameter9:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /all_in_one_ai/config/meta/industrial_model_table
      Type: String
      Value: !Sub all_in_one_ai_industrial_model

  Parameter10:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /all_in_one_ai/config/meta/model_table
      Type: String
      Value: all_in_one_ai_model

  Parameter11:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /all_in_one_ai/config/meta/pipeline/create_pipeline_helper_lambda_arn
      Type: String
      Value: !Ref CreatePipelineHelperLambdaArn

  Parameter12:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /all_in_one_ai/config/meta/pipeline_table
      Type: String
      Value: all_in_one_ai_pipeline

  Parameter13:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /all_in_one_ai/config/meta/training_job_table
      Type: String
      Value: all_in_one_ai_training_job

  Parameter14:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /all_in_one_ai/config/meta/transform_job_table
      Type: String
      Value: all_in_one_ai_transform_job

  Parameter15:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /all_in_one_ai/config/meta/algorithms/yolov5/industrialmodels
      Type: String
      Value: !Sub s3://${S3Bucket}/${S3Key}algorithms/yolov5/industrialmodels/

  Parameter16:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /all_in_one_ai/config/meta/algorithms/yolov5/source
      Type: String
      Value: !Sub s3://${S3Bucket}/${S3Key}algorithms/yolov5/source/sourcedir.tar.gz

  Parameter17:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /all_in_one_ai/config/meta/algorithms/yolov5/artifact
      Type: String
      Value: !Sub s3://${S3Bucket}/${S3Key}algorithms/yolov5/artifact/model.tar.gz

  Parameter18:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /all_in_one_ai/config/meta/algorithms/gluoncv/industrialmodels
      Type: String
      Value: !Sub s3://${S3Bucket}/${S3Key}algorithms/gluoncv/industrialmodels/

  Parameter19:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /all_in_one_ai/config/meta/algorithms/gluoncv/source
      Type: String
      Value: !Sub s3://${S3Bucket}/${S3Key}algorithms/gluoncv/source/sourcedir.tar.gz

  Parameter20:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /all_in_one_ai/config/meta/algorithms/gluoncv/artifact
      Type: String
      Value: !Sub s3://${S3Bucket}/${S3Key}algorithms/gluoncv/artifact/model.tar.gz

  Parameter21:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /all_in_one_ai/config/meta/algorithms/paddleocr/industrialmodels
      Type: String
      Value: !Sub s3://${S3Bucket}/${S3Key}algorithms/paddleocr/industrialmodels/

  Parameter22:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /all_in_one_ai/config/meta/algorithms/paddleocr/source
      Type: String
      Value: !Sub s3://${S3Bucket}/${S3Key}algorithms/paddleocr/source/sourcedir.tar.gz

  Parameter23:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /all_in_one_ai/config/meta/algorithms/paddleocr/artifact
      Type: String
      Value: !Sub s3://${S3Bucket}/${S3Key}algorithms/paddleocr/artifact/model.tar.gz

  Parameter24:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /all_in_one_ai/config/meta/algorithms/cpt/industrialmodels
      Type: String
      Value: !Sub s3://${S3Bucket}/${S3Key}algorithms/cpt/industrialmodels/

  Parameter25:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /all_in_one_ai/config/meta/algorithms/cpt/source
      Type: String
      Value: !Sub s3://${S3Bucket}/${S3Key}algorithms/cpt/source/sourcedir.tar.gz

  Parameter26:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /all_in_one_ai/config/meta/algorithms/cpt/artifact
      Type: String
      Value: !Sub s3://${S3Bucket}/${S3Key}algorithms/cpt/artifact/model.tar.gz

  Parameter27:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /all_in_one_ai/config/meta/algorithms/gabsa/industrialmodels
      Type: String
      Value: !Sub s3://${S3Bucket}/${S3Key}algorithms/gabsa/industrialmodels/

  Parameter28:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /all_in_one_ai/config/meta/algorithms/gabsa/source
      Type: String
      Value: !Sub s3://${S3Bucket}/${S3Key}algorithms/gabsa/source/sourcedir.tar.gz

  Parameter29:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /all_in_one_ai/config/meta/algorithms/gabsa/artifact
      Type: String
      Value: !Sub s3://${S3Bucket}/${S3Key}algorithms/gabsa/artifact/model.tar.gz

  Parameter30:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /all_in_one_ai/config/meta/algorithms/paddlenlp/industrialmodels
      Type: String
      Value: !Sub s3://${S3Bucket}/${S3Key}algorithms/paddlenlp/industrialmodels/

  Parameter31:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /all_in_one_ai/config/meta/algorithms/paddlenlp/source
      Type: String
      Value: !Sub s3://${S3Bucket}/${S3Key}algorithms/paddlenlp/source/sourcedir.tar.gz

  Parameter32:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /all_in_one_ai/config/meta/algorithms/paddlenlp/artifact
      Type: String
      Value: !Sub s3://${S3Bucket}/${S3Key}algorithms/paddlenlp/artifact/model.tar.gz

  Parameter33:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /all_in_one_ai/config/meta/algorithms/mdeberta/industrialmodels
      Type: String
      Value: !Sub s3://${S3Bucket}/${S3Key}algorithms/mdeberta/industrialmodels/