AWSTemplateFormatVersion: 2010-09-09
Description: Template for DynamoDB

Resources: 
  IndustrialModelDynamoDBTable: 
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - 
          AttributeName: "model_id"
          AttributeType: "S"
        - 
          AttributeName: "model_algorithm"
          AttributeType: "S"
      KeySchema: 
        - 
          AttributeName: "model_id"
          KeyType: "HASH"
        - 
          AttributeName: "model_algorithm"
          KeyType: "RANGE"
      ProvisionedThroughput: 
        ReadCapacityUnits: "1"
        WriteCapacityUnits: "1"
      TableName: "all_in_one_ai_industrial_model"

  ModelDynamoDBTable: 
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - 
          AttributeName: "model_name"
          AttributeType: "S"
        - 
          AttributeName: "industrial_model"
          AttributeType: "S"
      KeySchema: 
        - 
          AttributeName: "model_name"
          KeyType: "HASH"
        - 
          AttributeName: "industrial_model"
          KeyType: "RANGE"
      ProvisionedThroughput: 
        ReadCapacityUnits: "1"
        WriteCapacityUnits: "1"
      TableName: "all_in_one_ai_model"

  EndpointDynamoDBTable: 
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - 
          AttributeName: "endpoint_name"
          AttributeType: "S"
        - 
          AttributeName: "industrial_model"
          AttributeType: "S"
      KeySchema: 
        - 
          AttributeName: "endpoint_name"
          KeyType: "HASH"
        - 
          AttributeName: "industrial_model"
          KeyType: "RANGE"
      ProvisionedThroughput: 
        ReadCapacityUnits: "1"
        WriteCapacityUnits: "1"
      TableName: "all_in_one_ai_endpoint"

  TrainingJobDynamoDBTable: 
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - 
          AttributeName: "training_job_name"
          AttributeType: "S"
        - 
          AttributeName: "industrial_model"
          AttributeType: "S"
      KeySchema: 
        - 
          AttributeName: "training_job_name"
          KeyType: "HASH"
        - 
          AttributeName: "industrial_model"
          KeyType: "RANGE"
      ProvisionedThroughput: 
        ReadCapacityUnits: "1"
        WriteCapacityUnits: "1"
      TableName: "all_in_one_ai_training_job"

  TransformJobDynamoDBTable: 
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - 
          AttributeName: "transform_job_name"
          AttributeType: "S"
        - 
          AttributeName: "industrial_model"
          AttributeType: "S"
      KeySchema: 
        - 
          AttributeName: "transform_job_name"
          KeyType: "HASH"
        - 
          AttributeName: "industrial_model"
          KeyType: "RANGE"
      ProvisionedThroughput: 
        ReadCapacityUnits: "1"
        WriteCapacityUnits: "1"
      TableName: "all_in_one_ai_transform_job"

  ApiDynamoDBTable: 
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - 
          AttributeName: "api_name"
          AttributeType: "S"
        - 
          AttributeName: "industrial_model"
          AttributeType: "S"
      KeySchema: 
        - 
          AttributeName: "api_name"
          KeyType: "HASH"
        - 
          AttributeName: "industrial_model"
          KeyType: "RANGE"
      ProvisionedThroughput: 
        ReadCapacityUnits: "1"
        WriteCapacityUnits: "1"
      TableName: "all_in_one_ai_api"

  PipelineDynamoDBTable: 
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - 
          AttributeName: "pipeline_execution_arn"
          AttributeType: "S"
        - 
          AttributeName: "industrial_model"
          AttributeType: "S"
      KeySchema: 
        - 
          AttributeName: "pipeline_execution_arn"
          KeyType: "HASH"
        - 
          AttributeName: "industrial_model"
          KeyType: "RANGE"
      ProvisionedThroughput: 
        ReadCapacityUnits: "1"
        WriteCapacityUnits: "1"
      TableName: "all_in_one_ai_pipeline"

  WebSocketConnectionDBTable: 
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - 
          AttributeName: "connection_id"
          AttributeType: "S"
      KeySchema: 
        - 
          AttributeName: "connection_id"
          KeyType: "HASH"
      ProvisionedThroughput: 
        ReadCapacityUnits: "1"
        WriteCapacityUnits: "1"
      TableName: "all_in_one_ai_websocket_connection"

  ImportJobsDBTable: 
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - 
          AttributeName: "industrial_model"
          AttributeType: "S"
      KeySchema: 
        - 
          AttributeName: "industrial_model"
          KeyType: "HASH"
      ProvisionedThroughput: 
        ReadCapacityUnits: "1"
        WriteCapacityUnits: "1"
      TableName: "all_in_one_ai_import_jobs"

  SDModelDBTable: 
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        -
          AttributeName: "model_name"
          AttributeType: "S"
        -
          AttributeName: "endpoint_name"
          AttributeType: "S"
      KeySchema: 
        -
          AttributeName: "model_name"
          KeyType: "HASH"
        -
          AttributeName: "endpoint_name"
          KeyType: "RANGE"
      ProvisionedThroughput: 
        ReadCapacityUnits: "1"
        WriteCapacityUnits: "1"
      TableName: "all_in_one_ai_sd_model"

  SDUserDBTable: 
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - 
          AttributeName: "username"
          AttributeType: "S"
      KeySchema: 
        - 
          AttributeName: "username"
          KeyType: "HASH"
      ProvisionedThroughput: 
        ReadCapacityUnits: "1"
        WriteCapacityUnits: "1"
      TableName: "all_in_one_ai_sd_user"