AWSTemplateFormatVersion: "2010-09-09"
Description: Template for SQS
Parameters:
  ImportOpensearchSyncHelperFunctionArn:
    Type: String
    Description: ImportOpensearchSyncHelperFunction Arn

Resources: 
  AllInOneAIDLQ: 
    Type: AWS::SQS::Queue
    Properties: 
      QueueName: all_in_one_ai_dlq
      VisibilityTimeout: 900
  
  AllInOneAIQueue: 
    Type: AWS::SQS::Queue
    Properties: 
      QueueName: all_in_one_ai_sqs
      VisibilityTimeout: 900
      RedrivePolicy: 
        deadLetterTargetArn: !GetAtt AllInOneAIDLQ.Arn
        maxReceiveCount: 1000

  ImportOpensearchSyncHelperFunctionEventSourceMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 10
      Enabled: true
      FunctionResponseTypes: 
        - ReportBatchItemFailures
      EventSourceArn: !GetAtt AllInOneAIQueue.Arn
      FunctionName: !Ref ImportOpensearchSyncHelperFunctionArn
