FROM node:18
 
RUN mkdir -p /usr/src/app
WORKDIR /user/src/app
 
COPY . /user/src/app

RUN mkdir -p /user/src/app/images

RUN curl -o- -L https://yarnpkg.com/install.sh | bash
RUN $HOME/.yarn/bin/yarn install
RUN export NODE_OPTIONS=--openssl-legacy-provider && npm install -g webpack --registry=https://registry.npm.taobao.org && npm install --legacy-peer-deps --registry=https://registry.npm.taobao.org && yarn build
 
EXPOSE 3000

CMD ["node","run.js"]
